### ISSUE TITLE
[Problem]Minimum requirements is not updated

### ISSUE THREAD

**Issue by lezzokafka** [crypto-org-chain/cronos-docs#133]
**Problem:** 
  Besides `x86_64 architecture processor`, we also support ARM now:
  https://cronos.org/docs/getting-started/cronos-testnet.html#prepare-your-machine
  https://cronos.org/docs/getting-started/cronos-mainnet.html#prepare-your-machine

Solution:
Update it to `4-core, x86_64/ARM architecture processor`.

**Comment by aw126** [comment]
Updated with https://github.com/crypto-org-chain/cronos-docs/pull/135 & https://github.com/crypto-org-chain/cronos-docs/pull/134
