### ISSUE TITLE
Problem: devnet guides are not update to date

### ISSUE THREAD

**Issue by CeruleanAtMonaco** [crypto-org-chain/cronos-docs#48]
### Problem description:
Guides in https://cronos.crypto.org/docs/getting-started/local-devnet.html#customize-your-devnet are very off if to run it with the latest https://github.com/crypto-org-chain/cronos (commit https://github.com/crypto-org-chain/cronos/commit/793e340f5d60e057831359b2d6959f2b78a81373), e.g.  
1. root path is not `ethermint` anymore, 
2. there is no init.sh (probably missing) file at all now

**Comment by rarcif** [comment]
https://github.com/crypto-org-chain/cronos-docs/pull/60

**Comment by rarcif** [comment]
1. New folder is "cronos"
2. init.sh is missing. Probably outdated.

Tried to start with pystarport cmd as per yaml files in root/script folder.

pystarport serve --config ./scripts/cronos-devnet.yaml 
pystarport serve --config ./scripts/devnet.yaml 

The scripts do not start the node. We may have to look into the last stable setup to start the dev not. 

please note state as per attached screenshot.
<img width="1153" alt="Screenshot 2021-11-06 at 15 01 31" src="https://user-images.githubusercontent.com/92729550/140610558-fb3a9de3-05a8-4095-9d7d-e8d2160aa4f2.png">
