### ISSUE TITLE
Problem: EVM API is not documented on Cronos integration documentation

### ISSUE THREAD

**Issue by lezzokafka** [crypto-org-chain/cronos-docs#55]
**Problem** - 
No EVM API is documented on [Cronos Integration documentation](https://cronos.crypto.org/docs/resources/chain-integration.html#useful-links) 

**Solution** - 
Adding EVM API and examples to the Cronos Integration documentation, which should include:
- JSON-RPC Methods and some examples
- JSON-RPC Server
- JSON-RPC namespaces supported on Cronos

References can be found in  https://github.com/crypto-org-chain/cronos/tree/main/docs/api

**Comment by rarcif** [comment]
Done with adding the contents and formatting on my repo. Will test the endpoints before submitting PR
